export const GET_ALL_BUSINESS_DATA = "GET_ALL_BUSINESS_DATA";
export const GET_ALL_BUSINESS_DATA_ERROR = "GET_ALL_BUSINESS_DATA_ERROR";

export const GET_SEARCH_BUSINESS_RESULTS = "GET_SEARCH_BUSINESS_RESULTS";
export const GET_SEARCH_BUSINESS_RESULTS_ERROR = "GET_SEARCH_BUSINESS_RESULTS_ERROR";
