export const GET_ALL_BUSINESS_DATA = "GET_ALL_BUSINESS_DATA";
export const GET_ALL_BUSINESS_DATA_ERROR = "GET_ALL_BUSINESS_DATA_ERROR";

export const GET_SEARCH_BUSINESS_RESULTS_LOADING = "GET_SEARCH_BUSINESS_RESULTS_LOADING";
export const GET_SEARCH_BUSINESS_RESULTS_LOADED = "GET_SEARCH_BUSINESS_RESULTS_LOADED";
export const GET_SEARCH_BUSINESS_RESULTS_ERROR = "GET_SEARCH_BUSINESS_RESULTS_ERROR";

export const GET_ONE_BUSINESS_DETAILS_LOADING = "GET_ONE_BUSINESS_DETAILS_LOADING";
export const GET_ONE_BUSINESS_DETAILS_LOADED = "GET_ONE_BUSINESS_DETAILS_LOADED";
export const GET_ONE_BUSINESS_DETAILS_ERROR = "GET_ONE_BUSINESS_DETAILS_ERROR";
